version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MYSQL_HOST=db
      - MYSQL_DATABASE=cattuccino_bd
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  db:
    image: mysql:5.7
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cattuccino_bd
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./Database.sql:/docker-entrypoint-initdb.d/Database.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
